### ISSUE TITLE
Docker: возможность монтирования каталога os из хоста

### ISSUE THREAD

**Issue by allustin** [EvilBeaver/OneScript.Web#15]
сейчас предалагется

```
FROM evilbeaver/oscript-web:dev
COPY src /var/osp.net/
```

а хочется примерно так

```
docker run --port 5000:5000 --name my-super-onscript-webapp \
--volume ./://var/osp.net/engine/ evilbeaver/oscript-web:dev
```

или для docker-compose

```
version: '3'
services:
  web:
    image: evilbeaver/oscript-web:dev
     ports:
     - "5000:5000"
     volumes:
    - "./:/var/osp.net/engine/ "
```

тогда будет фактически доступен лайврелоад ;-)
