### ISSUE TITLE
Развертывание на heroku

### ISSUE THREAD

**Issue by pallid** [EvilBeaver/OneScript.Web#42]
Для развертывания приходится собирать свой образ, 
почему-то не развертывается если в сборке указан ENTRYPOINT

предварительно собирается образ
```docker
FROM mono:5.10

ENV LANG ru_RU.UTF-8
ADD artifact/net461/debian-x64 /var/osp.net
WORKDIR /app
``` 

далее как и было - только подменяем имя образа
```docker
FROM pallid/oscript-web-heroku:dev

COPY src /app
```

так же необходимо добавлять в корень репозитория файл heroky.yml
```yml
build:
  docker:
    web: Dockerfile
run:
  web: mono /var/osp.net/OneScript.WebHost.exe --urls http://*:$PORT
```
